// <auto-generated />
using System;
using APBDTEST2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APBDTEST2.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220609091930_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APBDTEST2.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            FirstName = "John",
                            LastName = "Maw"
                        },
                        new
                        {
                            IdClient = 2,
                            FirstName = "Sara",
                            LastName = "Curry"
                        });
                });

            modelBuilder.Entity("APBDTEST2.Models.ClientOrder", b =>
                {
                    b.Property<int>("IdClientOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdClientNavIdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployeeNavIdEmployee")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdClientOrder");

                    b.HasIndex("IdClientNavIdClient");

                    b.HasIndex("IdEmployeeNavIdEmployee");

                    b.ToTable("ClientOrders");

                    b.HasData(
                        new
                        {
                            IdClientOrder = 1,
                            Comments = "vlalvalal",
                            CompletionDate = new DateTime(2000, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClient = 1,
                            IdEmployee = 1,
                            OrderDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdClientOrder = 2,
                            Comments = "vlalvalal222222",
                            CompletionDate = new DateTime(2001, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClient = 2,
                            IdEmployee = 2,
                            OrderDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBDTEST2.Models.Confectionery", b =>
                {
                    b.Property<int>("IdConfectionery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("PricePerOne")
                        .HasColumnType("real");

                    b.HasKey("IdConfectionery");

                    b.ToTable("Confectioneries");

                    b.HasData(
                        new
                        {
                            IdConfectionery = 1,
                            Name = "Whatever1",
                            PricePerOne = 5f
                        },
                        new
                        {
                            IdConfectionery = 2,
                            Name = "Whatever2",
                            PricePerOne = 10f
                        });
                });

            modelBuilder.Entity("APBDTEST2.Models.Confectionery_ClientOrder", b =>
                {
                    b.Property<int>("IdClientOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdConfectionery")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("IdClientOrderNavIdClientOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdConfectioneryNavIdConfectionery")
                        .HasColumnType("int");

                    b.HasKey("IdClientOrder", "IdConfectionery")
                        .HasName("Confectionery_ClientOrder_PK");

                    b.HasIndex("IdClientOrderNavIdClientOrder");

                    b.HasIndex("IdConfectioneryNavIdConfectionery");

                    b.ToTable("ConfOrders");

                    b.HasData(
                        new
                        {
                            IdClientOrder = 1,
                            IdConfectionery = 1,
                            Amount = 1,
                            Comments = "dsasda"
                        },
                        new
                        {
                            IdClientOrder = 2,
                            IdConfectionery = 2,
                            Amount = 2,
                            Comments = "dsasda222222222"
                        });
                });

            modelBuilder.Entity("APBDTEST2.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdEmployee");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            IdEmployee = 1,
                            FirstName = "JohnE",
                            LastName = "MawE"
                        },
                        new
                        {
                            IdEmployee = 2,
                            FirstName = "SaraE",
                            LastName = "CurryE"
                        });
                });

            modelBuilder.Entity("APBDTEST2.Models.ClientOrder", b =>
                {
                    b.HasOne("APBDTEST2.Models.Client", "IdClientNav")
                        .WithMany("Orders")
                        .HasForeignKey("IdClientNavIdClient");

                    b.HasOne("APBDTEST2.Models.Employee", "IdEmployeeNav")
                        .WithMany("Orders")
                        .HasForeignKey("IdEmployeeNavIdEmployee");

                    b.Navigation("IdClientNav");

                    b.Navigation("IdEmployeeNav");
                });

            modelBuilder.Entity("APBDTEST2.Models.Confectionery_ClientOrder", b =>
                {
                    b.HasOne("APBDTEST2.Models.ClientOrder", "IdClientOrderNav")
                        .WithMany("ConfOrders")
                        .HasForeignKey("IdClientOrderNavIdClientOrder");

                    b.HasOne("APBDTEST2.Models.Confectionery", "IdConfectioneryNav")
                        .WithMany("ConfOrders")
                        .HasForeignKey("IdConfectioneryNavIdConfectionery");

                    b.Navigation("IdClientOrderNav");

                    b.Navigation("IdConfectioneryNav");
                });

            modelBuilder.Entity("APBDTEST2.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("APBDTEST2.Models.ClientOrder", b =>
                {
                    b.Navigation("ConfOrders");
                });

            modelBuilder.Entity("APBDTEST2.Models.Confectionery", b =>
                {
                    b.Navigation("ConfOrders");
                });

            modelBuilder.Entity("APBDTEST2.Models.Employee", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
